import type { Metadata } from "next";
import "./globals.css";
import "@/styles/general.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          as="image"
          href="/assets/hero-bg.svg"
          type="image/svg+xml"
        />
      </Head>
      <body className="scrollbar-hide">
        {children}
        {/* <RocketBackground /> */}
        {/* <DiffSection /> */}
      </body>
    </html>
  );
}
