import type { Metadata } from "next";
import "./globals.css";
import "@/styles/general.css";
import Navbar from "@/components/ui/navbar";
import { HeroSection } from "@/components/ui/heroSection";
import { Container } from "@/components/container";
import Head from "next/head";
import { ServicesSection } from "@/components/ui/servicesSection";
import FeatureHome from "@/components/ui/featureHome";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          as="image"
          href="/assets/hero-bg.svg"
          type="image/svg+xml"
        />
      </Head>
      <body>
        <Container className="h-screen bg-[url('../assets/hero-bg.svg')] bg-no-repeat bg-center bg-[length:auto_100%]">
          <Navbar />
          <HeroSection />
        </Container>
        <ServicesSection />
        <FeatureHome />
      </body>
    </html>
  );
}
